### ISSUE TITLE
.vagrant folder is being generated in several places.

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/vagrant#115] opened 2018-07-28 04:50 UTC
For example, if CC is launched from shortcut in desktop, .vagrant folder will appear in desktop too.

**Comment by Almansherov** [comment] 2018-09-11 11:31
After I created a VM using virtualbox and the vagrant plugin, I checked the directory for the additional folders and files. 
Result: Got nothing:



![image](https://user-images.githubusercontent.com/32430693/45357524-1bb9a400-b58c-11e8-8c3d-5e590df6df21.png)

So the issue is fixed on master

**Comment by kurmanbekova6** [comment] 2018-11-15 06:35
![screenshot from 2018-11-15 12-35-03](https://user-images.githubusercontent.com/9501291/48534657-ea828a80-e8d2-11e8-83b0-b456c75bcb1a.png)
Tested in prod

**Closed by kurmanbekova6** 2018-11-15 06:35 UTC
